### PR TITLE
Map save/load

### PR DESCRIPTION
**Pull request by r7vme**
Hi, as outcome from discussion here https://github.com/appliedAI-Initiative/orb_slam_2_ros/issues/19

Few notes:
- I'm totally open for any comments and improvements as initially code was intended for personal use
- May be "Map.mapfile" should be moved into ROS parameter as yaml file is cvFilestorage file, not really intended for any params. I decided  to have "save_map" as part of ROS already, so now it's kinda misaligned.
- Not all config files updates
- Examples also not updated
- Only tested mononode

### CODE REVIEW

**Comment by lennarthaller** [comment]
We now have basically two PRs implementing the same thing. This one and #31 :)

**Comment by r7vme** [comment]
hehe, i've tested on kitti odometry sequence 06 resulted map is around 130MB. It's quite small seq tho.

I'm ok to close my PR actually, as i see in https://github.com/appliedAI-Initiative/orb_slam_2_ros/pull/31 he already implemented configuration (save/load) via ROS params.

**Comment by BBO-repo** [comment]
Hi @r7vme,
I've tested your code with rgbd node on a small run (10min) and it seems ok
Just avoid from killing ros if bundle adjustment in progress else ros will quit before map being saved

I've tested with a long run (1hour), the map could not have been saved entirely because ros is killing cf. print screen
Nevertheless the bin saved map is a 878MB file I presume that ros killing while we are still writting the map.

If there is a way to force ros to wait map writing is finished then it could be ok.
Any suggestions?

image

**Comment by lennarthaller** [comment]
I suggest that instead of writing the map on shutdown we provide a ROS service to save the map. This gives us as much time as we need for writing to file and it puts the user in charge if he wants the file or not.
Then there is no need to decide before running the node if the map is going to be saved or not in the launch file.

**Comment by r7vme** [comment]
Hey @lennarthaller @BBO-repo i wanna close my PR in favor https://github.com/appliedAI-Initiative/orb_slam_2_ros/pull/31 as they are almost identical. Unfortunately i have not so much time to work on ROS service and proper testing. I hope @BBO-repo have some time. Let me know if i can help somehow.

**Comment by BBO-repo** [comment]
Ok I'll see to write a ROS service to request a map save and see if it ok with a big map.

**Comment by kouui** [comment]
Thanks for developing this user-friendly ROS version ORB-SLAM2.

I have a problem in "loop closing with preloaded map" in using `orb_slam2_mono`: **after loading the map SLAM mode works well, however,  local mapping will stop when updating map during loop closing. As a result, system will totally stop working**. Output of terminal is pasted below
```
Input sensor was set to: Monocular

Loading ORB Vocabulary.
Vocabulary loaded!

Loading map file: /home/ubuntu/savefiles/street_s60d260.bin ... done
Map reconstructing ... done
Using loaded map with 4367 points


Camera Parameters: 
- fx: 688.304
- fy: 689.185
- cx: 314.905
- cy: 251.142
- k1: -0.035728
- k2: 0.138006
- p1: 0.005212
- p2: -0.000513
- fps: 20
- color order: RGB (ignored if grayscale)

ORB Extractor Parameters: 
- Number of Features: 1000
- Scale Levels: 8
- Scale Factor: 1.2
- Initial Fast Threshold: 20
- Minimum Fast Threshold: 7
Enable localization only: false
New Map created with 4474 points
Loop detected!
Local Mapping STOP
Local Mapping RELEASE
Starting Global Bundle Adjustment
Global Bundle Adjustment finished
Updating map ...
Local Mapping STOP
``` 

Can anyone figure out what is going wrong?
Thanks for your attention to this matter.

**Pull request closed without merging**
