### PR TITLE
Save load

### PR DESCRIPTION
**Pull request by BBO-repo**
Hello Lennart,

Can you please find my integration map save and load based on Alkaid repo with boost binary serialization
I've added the orb_slam2_d435i_rgbd.launch file to illustrate the additional parameters

Then to allow save map, the configuration on launch file should be:
<param name="localize_only" type="bool" value="false" />
<param name="save_map" type="bool" value="true" />
<param name="load_map" type="bool" value="false" />
<param name="map_file" type="string" value="map.bin" />

Then to allow load map, the configuration on launch file should be:
<param name="localize_only" type="bool" value="true" />
<param name="save_map" type="bool" value="false" />
<param name="load_map" type="bool" value="true" />
<param name="map_file" type="string" value="map.bin" />

### CODE REVIEW

**Comment by lennarthaller** [comment]
Thank you very much for this PR! :) Check out #32 for a discussion.

**Comment by lennarthaller** [comment]
According to you there are still some errors with large maps in this code right?

**Comment by BBO-repo** [comment]
Yes that it.
For a run of about half an hour map saving and loading is ok
But with a run about a hour, map saving has problem .. not all of the map is saved and load the map then give errors.
Ok I'll try the second merge request with a long run and I'll keep you inform

**Comment by r7vme** [comment]
I (second PR) use same original code, so i assume results will be the same. I have only few minutes video (kitti odom 06) that i was testing with.

**Comment by BBO-repo** [comment]
Hi @r7vme,
I've tested your code with rgbd node on a small run (10min) and it seems ok
Just avoid from killing ros if bundle adjustment in progress else ros will quit before map being saved 
I am testing with a long run (1hour)

**Comment by lennarthaller** [comment]
It is a little confusing that we are discussing #32 here :D
Nevertheless I suggest that instead of writing the map on shutdown we provide a ROS service to save the map.

**Comment by BBO-repo** [comment]
@lennarthaller 
In fact you're right sorry .. I'll move the comment on other PR as those testing is about the PR #32

**Comment by lennarthaller** [comment]
@BBO-repo no problem!
Thanks

**Comment by lennarthaller** [comment]
@BBO-repo as #32 is closed, can you figure out why it worked there for larger sequences and then fix the error here?

**Comment by BBO-repo** [comment]
@lennarthaller 
I'll try to see with both PR #31 and #32 to write a service for map saving and then keep you inform if it solve large sequence map saving errors

**Comment by lennarthaller** [comment]
Awesome!

**Comment by lennarthaller** [comment]
I am going to go ahead an merge this to the feature branch even though not all issues are resolved. Let me know when you have new findings!

**Comment by lennarthaller** [comment]
Is there a reason why the default after a map load is hard coded to LocalizeOnly mode?

**Comment by BBO-repo** [comment]
Hi @lennarthaller,
Sorry for the delayed answer.
It is not necessary to force LocalizeOnly mode when using existing map.
It is only that in my case when I have a existing map, I just want to use it and localize but in fact existing preloaded map could also be updated, then the LocalizeOnly mode could not be forced
Could you test map saving with "big" map ?

**Comment by lennarthaller** [comment]
No worries.
Yes, I am happy to announce that the save and load feature is now fully supported, even on large maps. Enjoy!

**Comment by BBO-repo** [comment]
Ok thanks for your feedback.
I'll test tomorrow and keep you inform

**Comment by BBO-repo** [comment]
Hi @lennarthaller 
I confirm you that I was able to save a (big) map 1.1GB and load it and run in localize mode only.
Thanks

**Pull request merged**
